baseurl: https://rushionn.github.io.git
languageCode: en-us
theme: hugo-theme-stack
paginate: 5
title: プルスウルトラ

languages:
    en:
        languageName: 首頁
        title: プルスウルトラ
        weight: 1
    cn:
        languageName: 未建置
        title: プルスウルトラ
        weight: false
    ar:
        languageName: 未建置
        languagedirection: rtl
        title: موقع تجريبي
        weight: false

# Change it to your Disqus shortname before using
disqusShortname: rushionn

# GA Tracking ID
googleAnalytics: G-FNDM35MCGM

# Theme i18n support
# Available values: en, fr, id, ja, ko, pt-br, zh-cn, zh-tw, es, de, nl, it, th, el, uk, ar
DefaultContentLanguage: en

# Set hasCJKLanguage to true if DefaultContentLanguage is in [zh-cn ja ko]
# This will make .Summary and .WordCount behave correctly for CJK languages.
hasCJKLanguage: false

permalinks:
    post: /p/:slug/
    page: /:slug/

params:
    mainSections:
        - post
    featuredImageField: image
    rssFullContent: true
    favicon: img/mabinogi.png

    footer:
        since: 2022
        customText:

    dateFormat:
        published: Jan 02, 2006
        lastUpdated: Jan 02, 2006 15:04 MST

    sidebar:
        emoji: false
        subtitle: 千錘百鍊??
        avatar:
            enabled: true
            local: true
            src: img/umi.jpeg

    article:
        math: false
        toc: true
        readingTime: true
        license:
            enabled: true
            default: Licensed under CC BY-NC-SA 4.0

    comments:
        enabled: true
        provider: disqus

        disqusjs:
            enable: true
            shortname: rushionn
            apiUrl: 
            apiKey: 
            admin: 
            adminLabel: 

        utterances:
            repo:
            issueTerm: pathname
            label:

        remark42:
            host:
            site:
            locale:

        vssue:
            platform:
            owner:
            repo:
            clientId:
            clientSecret:
            autoCreateIssue: false

        # Waline client configuration see: https://waline.js.org/en/reference/client.html
        waline:
            serverURL:
            lang:
            visitor:
            avatar:
            emoji:
                - 
            requiredMeta:
                - name
                - email
                - url
            placeholder:
            locale:
                admin: 

        twikoo:
            envId:
            region:
            path:
            lang:

        # See https://cactus.chat/docs/reference/web-client/#configuration for description of the various options
        cactus:
            defaultHomeserverUrl: 
            serverName: 
            siteName: "" # You must insert a unique identifier here matching the one you registered (See https://cactus.chat/docs/getting-started/quick-start/#register-your-site)

        giscus:
            repo:
            repoID:
            category:
            categoryID:
            mapping:
            lightTheme:
            darkTheme:
            reactionsEnabled: 1
            emitMetadata: 0

        gitalk:
            owner:
            admin:
            repo:
            clientID:
            clientSecret:

        cusdis:
            host:
            id:
    widgets:
        homepage:
            - type: 
            - type: archives
              params:
                  limit: 5
            - type: categories
              params:
                  limit: 5
            - type: tag-cloud
              params:
                  limit: 10
        page:
            - type: toc

    opengraph:
        twitter:
            # Your Twitter username
            site:

            # Available values: summary, summary_large_image
            card: summary_large_image

    defaultImage:
        opengraph:
            enabled: true
            local: true
            src: "src/spiderman1.gif"

    colorScheme:
        # Display toggle
        toggle: true

        # Available values: auto, light, dark
        default: dark

    imageProcessing:
        cover:
            enabled: true
        content:
            enabled: true

### Custom menu
### See https://docs.stack.jimmycai.com/configuration/custom-menu.html
### To remove about, archive and search page menu item, remove `menu` field from their FrontMatter
menu:
    main: []

    social:
        - identifier: github
          name: GitHub
          url: https://github.com/rushionn/rushionn.github.io
          params:
              icon: github

        - identifier: twitter
          name: Twitter
          url: https://twitter.com/umiwued
          params:
              icon: twitter

        - identifier: instergram
          name: Instergram
          url: https://www.instagram.com/yidiwu1108/
          params: 
              icon: instergram

        - identifier: youtube
          name: Youtube
          url: https://www.youtube.com/channel/UCCyqyVr_zW8srGEhSOM3VYw
          params:
              icon: youtube

        - identifier: discord
          name: Discord
          url: https://rushionn.github.io
          params: 
              icon: discord

related:
    includeNewer: true
    threshold: 60
    toLower: false
    indices:
        - name: tags
          weight: 100

        - name: categories
          weight: 200

markup:
    goldmark:
        renderer:
            ## Set to true if you have HTML content inside Markdown
            unsafe: true
    tableOfContents:
        endLevel: 4
        ordered: true
        startLevel: 2
    highlight:
        noClasses: false
        codeFences: true
        guessSyntax: true
        lineNoStart: 1
        lineNos: true
        lineNumbersInTable: true
        tabWidth: 4

